### ISSUE TITLE
Telegraf Input

### ISSUE THREAD

**Issue by pbegg** [KEGustafsson/influxdbv2-test-docker#1]
I'm very happy I have come across your repo.
Not an issue however could you please clarify how the telegraf input plugin works in this instance? 
How do you get from urls = ["http://localhost:3000/signalk/v1/api/vessels/self"] to a valid JSON input for telegraf?

**Comment by KEGustafsson** [comment]
Hi,
Target was to used this with existing/already running Signal K server. Data would be coming then from server REST API in JSON format. Telegraf [[[inputs.http]]](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http) is then used for reading that data in.

I added a [Full](https://github.com/KEGustafsson/influxdbv2-test-docker/tree/full) branch, which contains also Signal K setup. With that there is no external dependencies.

**Comment by pbegg** [comment]
Thanks for the quick response. I have signalk running separately. I think I worded my question poorly. an example if you use the input address as "http://localhost:3000/signalk/v1/api/vessels/self/navigation" you get the response:

`{"speedOverGround":{"meta":{"units":"m/s","description":"Vessel speed over ground. If converting from AIS 'HIGH' value, set to 102.2 (Ais max value) and add warning in notifications"},"value":0.8,"$source":"essense-simulate-paths.XX","timestamp":"2021-01-18T22:09:34.928Z"}}`

how does telegraf then know how to convert this to a correct format to save it into an influxdb database?

**Comment by KEGustafsson** [comment]
In your example, there is one key and respective value. It would be then in `navigation_speedOverGround_value` and value would be `0.8` in the database/measurement that you have defined earlier.

Telegraf input plugin, [HTTP Input Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http), read/parse key/value pairs from e.g. json and then telegraf is able to output data in normal line format to InfluxDB.

I'm currently logging from path `/signalk/v1/api/vessels/self` and here is an example of my live data how it would look like in Grafana, [speedOverGround](https://github.com/KEGustafsson/influxdbv2-test-docker/blob/full/doc/jsonToInflux.jpg). Boat is winterized and therefore speed is 0 or close.

**Comment by pbegg** [comment]
I have been reading into this quite a lot today, and now understand the HTTP input plugin quite a bit more. I am also trying to log from the same path. `/signalk/v1/api/vessels/self`

How do you handle multiple values for the same path? eg. 2 or 3 GPS sources, or only log selected paths? it starts to get very messy with the names of the measurement, see attached picture.

Do you edit the json_query parameter in the telegraf.conf to filter the data?
![image](https://user-images.githubusercontent.com/52762086/105009984-49ce1d80-5a8f-11eb-9f87-09e0fb484698.png)

**Comment by KEGustafsson** [comment]
I'm using the the very same `telegraf.conf` that you can find from this repository.

To filter out multiple data sources, Signal K has feature called `Source Priorities Settings`. You can find it under `Server/Data Connections`. There you can make priorities to multiple data sources and output can be seen from REST API. Only the highest priority data source will be available. It has still experimental badge, but that will be removed in next server release. I have been using this from very beginning and it is working very well.
As you might have seen that multiple GPS/GNSS have bit offset/error to each other and that might lead to location to jump randomly. This will eliminate that problem.
